{% set name = "powerpax" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/powerpax-{{ version }}.tar.gz
  sha256: 64cc6843a68286a5ed3557e2b5b55cd2266b2064a8067d97fae1adb059eae9b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.4.6

test:
  imports:
    - powerpax
  commands:
    - pip check
    - JAX_ENABLE_X64=True pytest tests  # [unix]
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/karlotness/powerpax
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    A collection of utility functions for JAX.
  summary: Small collection of useful utilities for JAX
  doc_url: https://powerpax.readthedocs.io/
  dev_url: https://github.com/karlotness/powerpax

extra:
  recipe-maintainers:
    - karlotness
