{% set name = "powerpax" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/powerpax-{{ version }}.tar.gz
  sha256: f4f2a40a3531b9d2aae5c6fcdb5016fcf4f8bf6c384d78a29247ea5b831df328

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9
    - jax >=0.4.6

test:
  imports:
    - powerpax
  commands:
    - pip check
    - JAX_ENABLE_X64=True pytest tests  # [unix]
  source_files:
    - tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/karlotness/powerpax
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    A collection of utility functions for JAX.
  summary: Small collection of useful utilities for JAX
  doc_url: https://powerpax.readthedocs.io/
  dev_url: https://github.com/karlotness/powerpax

extra:
  recipe-maintainers:
    - karlotness
